---
RecipeFormatVersion: '2020-01-25'
ComponentName: aws.greengrass.labs.database.PostgreSQL
ComponentVersion: '1.0.0'
ComponentDescription: 'A component that provisions and manages a local PostgreSQL instance in a Docker container.'
ComponentPublisher: Amazon
Manifests:
  - Platform:
      os: /darwin|linux/
    Lifecycle:
      Run:
        script: |-
          python3 -u {artifacts:decompressedPath}/aws-greengrass-labs-database-postgresql/src/manage_postgresql.py
    Artifacts:
      - URI: s3://aws-greengrass-labs-database-postgresql.zip
        Unarchive: ZIP
